# Generated by Django 2.2b1 on 2019-02-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='已测试的用户名')),
                ('password', models.CharField(max_length=20, verbose_name='已测试的密码')),
                ('test_pass', models.IntegerField(verbose_name='测试是否通过')),
            ],
        ),
    ]
