# Generated by Django 2.2b1 on 2019-03-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_ip', models.CharField(max_length=80, verbose_name='被测试的站点')),
                ('username', models.CharField(max_length=100, verbose_name='已测试的用户名')),
                ('password', models.CharField(max_length=100, verbose_name='已测试的密码')),
                ('login_status', models.IntegerField(verbose_name='登录状态')),
                ('problem_id', models.IntegerField(default=1000, verbose_name='问题id')),
                ('problem_status', models.SmallIntegerField(verbose_name='问题运行状态')),
                ('problem_res', models.CharField(max_length=100, verbose_name='问题运行结果')),
                ('start_end_time', models.IntegerField(verbose_name='测试用时')),
                ('atetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcesssPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_process', models.CharField(max_length=100, verbose_name='主进程，节点名')),
                ('strecondary_process', models.CharField(max_length=100, verbose_name='副进程，控制台名')),
                ('from_process', models.CharField(max_length=100, verbose_name='从进程，进程名')),
                ('start_end_time', models.IntegerField(verbose_name='测试用时')),
                ('site_ip', models.CharField(max_length=100, verbose_name='被测试的站点')),
            ],
        ),
        migrations.CreateModel(
            name='SiteServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_ip', models.CharField(max_length=80, verbose_name='被测试的站点')),
                ('service_ip', models.CharField(max_length=100, verbose_name='服务器ip')),
                ('service_username', models.CharField(max_length=100, verbose_name='服务器用户名')),
                ('service_pwd', models.CharField(max_length=100, verbose_name='服务器密码')),
                ('service_port', models.CharField(max_length=100, verbose_name='服务器端口')),
                ('use_datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_ip', models.CharField(max_length=80, verbose_name='被测试的站点')),
                ('time_data', models.CharField(max_length=255, verbose_name='获取的服务器状态')),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_ip', models.CharField(max_length=100, verbose_name='被测试的站点')),
                ('username', models.CharField(max_length=100, verbose_name='已测试的用户名')),
                ('password', models.CharField(max_length=100, verbose_name='已测试的密码')),
                ('test_sign', models.IntegerField(verbose_name='测试注册成功')),
                ('test_login', models.IntegerField(verbose_name='登录次数')),
            ],
        ),
    ]
