# Generated by Django 2.2b1 on 2019-03-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActivityModel', '0002_testsql'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginproblem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='processspart',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='testservice',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
