# Generated by Django 2.2b1 on 2019-03-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActivityModel', '0003_auto_20190302_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testservice',
            name='time_data',
            field=models.CharField(max_length=255, verbose_name='获取的服务器状态'),
        ),
    ]
